# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    http_client:
        default_options:
            max_redirects: 5
        scoped_clients:
            # Specialized client to consume the Client
            xm_client:
                timeout: 10
                base_uri: 'https://google.com'
                headers:
                    'Accept': 'application/vnd.github.v3+json'
                    'Content-Type': 'application/json'
                    'test1': 'test2'
                    # 'Authorization': 'token %env(GITHUB_API_TOKEN)%'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

when@prod:
    framework:
        http_cache: true