controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

kernel:
    resource: App\Kernel
    type: attribute

consume_api:
    path: /
    controller: App\Controller\FormController::index

historical_api:
    path: /historical/{endDate}/{startDate}
    controller: App\Controller\FormController::historical
    requirements:
    methods: GET
